"""Primera migración

Revision ID: 9f99a98f902f
Revises: 
Create Date: 2025-05-08 09:41:13.157558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f99a98f902f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help',
    sa.Column('id_help', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_help')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chat',
    sa.Column('id_chat', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=150), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_chat')
    )
    op.create_table('message',
    sa.Column('id_message', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_chat', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=150), nullable=True),
    sa.Column('type', sa.String(length=150), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_chat'], ['chat.id_chat'], ),
    sa.PrimaryKeyConstraint('id_message')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('chat')
    op.drop_table('user')
    op.drop_table('help')
    # ### end Alembic commands ###
