"""Add response column to message 

Revision ID: ce078a057113
Revises: 9f99a98f902f
Create Date: 2025-05-13 11:50:14.192967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce078a057113'
down_revision: Union[str, None] = '9f99a98f902f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('response', sa.Text(), nullable=True))
    op.alter_column('message', 'content',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'content',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.drop_column('message', 'response')
    # ### end Alembic commands ###
